---
title: "2020-08-Tidymodels"
author: "Johnathon A de Villier"
date: "8/29/2020"
output: html_document
---

```{r}
<<<<<<< HEAD

# install.packages("tidymodels")
# install.packages("readxl")
# install.packages("broom.mixed")

# libraries
library(tidymodels)
library(tidyr)
library(dplyr)
library(stringr)
library(readxl)
library(readr)

```

# Part 1: Building a model
https://www.tidymodels.org/start/models/

## shortcuts: 
cmd+opt+I = insert new chunk
cmd+opt+C = run current chunk

```{r}
# import data
urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv") %>% 
  # rename and factor columns
  setNames(c("food_regime", "initial_volume", "width")) %>%
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

head(urchins)

# plot the urchins data
ggplot(urchins, aes(x = initial_volume, y = width,
                    group = food_regime, color = food_regime)) +
  geom_point() +
  geom_smooth(method = 'lm', se = F) +
  scale_color_viridis_d(option = 'plasma', end = .7)

```

# Building a linear regression model with parsnip

```{r}

# 1) specify the form of model to use for the analysis
lm_mod <- linear_reg() %>% 
  set_engine("lm")

# 2) train the model using fit()
lm_fit <- 
  lm_mod %>% 
  fit(width ~ initial_volume * food_regime, data = urchins)

# to return model results in a tibble, use tidy()
tidy(lm_fit)

# PREDICTING NEW VALUES

# 3) create a data frame to house values we want to predict
new_points <- expand.grid(initial_volume = 20,
                          food_regime = c('Initial', 'Low', 'High'))

# 4) predict values at new points using the model object
urchins_mean_pred <- predict(lm_fit, new_data = new_points)
urchins_mean_pred

# 5) calculate standard error
conf_int_urchins_mean_pred <- predict(lm_fit,
                                      new_data = new_points,
                                      type = 'conf_int')
conf_int_urchins_mean_pred

# 6) combine predicted results and error into a single tibble
urchins_plot <- new_points %>% 
  bind_cols(urchins_mean_pred,
            conf_int_urchins_mean_pred)

# 7) plot the results
ggplot(urchins_plot, aes (x = food_regime)) +
  geom_point(aes(y = .pred)) +
  geom_errorbar(aes(ymin = .pred_lower,
                    ymax = .pred_upper),
                width = .1) +
  labs(y = 'urchin size')



=======

# install.packages("tidymodels")
# install.packages("readxl")
# install.packages("broom.mixed")

# libraries
library(tidymodels)
library(tidyr)
library(dplyr)
library(stringr)
library(readxl)
library(readr)

```

# Part 1: Building a model
https://www.tidymodels.org/start/models/

## shortcuts: 
cmd+opt+I = insert new chunk
cmd+opt+C = run current chunk

```{r}
# import data
urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv") %>% 
  # rename and factor columns
  setNames(c("food_regime", "initial_volume", "width")) %>%
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

head(urchins)

# plot the urhcins data
ggplot(urchins, aes(x = initial_volume, y = width,
                    group = food_regime, color = food_regime)) +
  geom_point() +
  geom_smooth(method = 'lm', se = F) +
  scale_color_viridis_d(option = 'plasma', end = .7)
>>>>>>> 0fd62bb8039d65c258959a9c170c0f0526b9f936
```

